// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdTERRh-9wveKt4UbvfU2xsp-58VJYBNA',
    appId: '1:207653257384:web:73933026662ddf49dac29d',
    messagingSenderId: '207653257384',
    projectId: 'kiit-kiit',
    authDomain: 'kiit-kiit.firebaseapp.com',
    databaseURL: 'https://kiit-kiit-default-rtdb.firebaseio.com',
    storageBucket: 'kiit-kiit.firebasestorage.app',
    measurementId: 'G-BPJLM4N29C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvhMFz6O3pdNlGMU-Vttuoe69U8w_wou0',
    appId: '1:207653257384:android:be97368575c6454bdac29d',
    messagingSenderId: '207653257384',
    projectId: 'kiit-kiit',
    databaseURL: 'https://kiit-kiit-default-rtdb.firebaseio.com',
    storageBucket: 'kiit-kiit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPBdq8FqcAk_qe0EEIN0ppM8mgHDL7ZCU',
    appId: '1:207653257384:ios:0d4e4cca1f038fbfdac29d',
    messagingSenderId: '207653257384',
    projectId: 'kiit-kiit',
    databaseURL: 'https://kiit-kiit-default-rtdb.firebaseio.com',
    storageBucket: 'kiit-kiit.firebasestorage.app',
    iosBundleId: 'com.example.azyq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPBdq8FqcAk_qe0EEIN0ppM8mgHDL7ZCU',
    appId: '1:207653257384:ios:0d4e4cca1f038fbfdac29d',
    messagingSenderId: '207653257384',
    projectId: 'kiit-kiit',
    databaseURL: 'https://kiit-kiit-default-rtdb.firebaseio.com',
    storageBucket: 'kiit-kiit.firebasestorage.app',
    iosBundleId: 'com.example.azyq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdTERRh-9wveKt4UbvfU2xsp-58VJYBNA',
    appId: '1:207653257384:web:60de2f76c00ddcf2dac29d',
    messagingSenderId: '207653257384',
    projectId: 'kiit-kiit',
    authDomain: 'kiit-kiit.firebaseapp.com',
    databaseURL: 'https://kiit-kiit-default-rtdb.firebaseio.com',
    storageBucket: 'kiit-kiit.firebasestorage.app',
    measurementId: 'G-8SQWXD7XTZ',
  );

}